const ADD_NOTE = 'ADD_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const CHANGE_CURRENT_TAG = 'CHANGE_CURRENT_TAG';
const IS_ACTIVE = 'IS_ACTIVE';

export {
  ADD_NOTE,
  DELETE_NOTE,
  CHANGE_CURRENT_TAG,
  IS_ACTIVE,
};
